### ISSUE TITLE
missing rights for a role

### ISSUE THREAD

**Issue by Janitsu** [Thoumey/bot-leo#4]
https://github.com/Thoumey/bot-leo/blob/a0e525272f4d3c26a0f4ef20bf29333b4ebc4b24/index.js#L102

should add the role id of "bink" to avoid common problems (i.e. complaints on discord or lack of service provided)

do not have access to the role id but will be happy to provide a solution once said id is provided

**Comment by Thoumey** [comment]
fixed in 5bb8a88
